import React from 'react';
import { Download, Edit, Trash2, Calendar, Tag, Star, CheckCircle, Target } from 'lucide-react';
import { Situation } from '../types';
import { frameworks } from '../data/frameworks';

interface ReflectionSummaryProps {
  reflection: Situation;
  onEdit?: () => void;
  onDelete?: () => void;
  onExport?: () => void;
}

export function ReflectionSummary({ reflection, onEdit, onDelete, onExport }: ReflectionSummaryProps) {
  const framework = frameworks[reflection.framework];
  const createdDate = new Date(reflection.createdAt).toLocaleDateString();

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'feedback': return 'from-blue-400 to-blue-600';
      case 'conflict': return 'from-red-400 to-red-600';
      case 'decision': return 'from-purple-400 to-purple-600';
      case 'stakeholder': return 'from-green-400 to-green-600';
      case 'team-dynamics': return 'from-orange-400 to-orange-600';
      case 'other': return 'from-gray-400 to-gray-600';
      default: return 'from-blue-400 to-blue-600';
    }
  };

  const getCategoryEmoji = (category: string) => {
    switch (category) {
      case 'feedback': return '💬';
      case 'conflict': return '🤝';
      case 'decision': return '🎯';
      case 'stakeholder': return '🌐';
      case 'team-dynamics': return '👥';
      case 'other': return '⚡';
      default: return '📝';
    }
  };

  const exportToPDF = () => {
    let content = `🚀 Leadership Reflection - ${framework.name}\n`;
    content += `📅 Created: ${createdDate}\n`;
    content += `📂 Category: ${getCategoryEmoji(reflection.category)} ${reflection.category}\n\n`;
    content += `📋 Framework: ${framework.name}\n`;
    content += `📝 Description: ${framework.description}\n\n`;
    content += `═══════════════════════════════════════\n\n`;
    
    framework.questions.forEach((question, index) => {
      const response = reflection.responses[question.id] || 'No response';
      content += `❓ Question ${index + 1}: ${question.text}\n`;
      content += `💭 Response: ${response}\n\n`;
    });

    content += `═══════════════════════════════════════\n`;
    content += `✨ Generated by Reflect & Act - Your Leadership Learning Companion\n`;
    content += `🔒 This reflection was created privately and securely on your device.`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `reflection-${reflection.id}-${createdDate.replace(/\//g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden hover:shadow-md transition-all duration-200">
      {/* Header */}
      <div className={`bg-gradient-to-r ${getCategoryColor(reflection.category)} text-white p-6`}>
        <div className="flex justify-between items-start mb-4">
          <div className="flex items-start gap-4">
            <div className="text-4xl">{getCategoryEmoji(reflection.category)}</div>
            <div>
              <h2 className="text-2xl font-semibold mb-2">
                {reflection.title || framework.name}
              </h2>
              <div className="flex items-center gap-4 text-sm text-white text-opacity-90">
                <div className="flex items-center gap-1">
                  <Calendar className="w-4 h-4" />
                  <span>{createdDate}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Tag className="w-4 h-4" />
                  <span className="capitalize">{reflection.category}</span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {onEdit && (
              <button
                onClick={onEdit}
                className="p-3 bg-white bg-opacity-20 hover:bg-opacity-30 rounded-lg transition-all duration-200"
                title="Edit reflection"
              >
                <Edit className="w-4 h-4" />
              </button>
            )}
            <button
              onClick={exportToPDF}
              className="p-3 bg-white bg-opacity-20 hover:bg-opacity-30 rounded-lg transition-all duration-200"
              title="Export reflection"
            >
              <Download className="w-4 h-4" />
            </button>
            {onDelete && (
              <button
                onClick={onDelete}
                className="p-3 bg-white bg-opacity-20 hover:bg-opacity-30 rounded-lg transition-all duration-200"
                title="Delete reflection"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>
        
        <div className="bg-white bg-opacity-20 backdrop-blur-sm p-4 rounded-xl">
          <p className="text-white text-sm">
            <strong>Framework:</strong> {framework.description}
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="p-6 space-y-6">
        {framework.questions.map((question, index) => {
          const response = reflection.responses[question.id];
          if (!response?.trim()) return null;
          
          return (
            <div key={question.id} className="bg-gray-50 p-6 rounded-xl border-l-4 border-blue-500">
              <div className="flex items-start gap-4">
                <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-indigo-600 rounded-full flex items-center justify-center text-white font-bold text-sm flex-shrink-0">
                  {index + 1}
                </div>
                <div className="flex-1">
                  <h3 className="font-semibold text-gray-900 mb-3">
                    {question.text}
                  </h3>
                  <p className="text-gray-700 whitespace-pre-wrap leading-relaxed">
                    {response}
                  </p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Footer */}
      <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className={`flex items-center gap-2 px-3 py-1 rounded-full text-sm font-medium ${
              reflection.status === 'completed' 
                ? 'bg-green-100 text-green-800' 
                : 'bg-amber-100 text-amber-800'
            }`}>
              {reflection.status === 'completed' ? (
                <>
                  <CheckCircle className="w-4 h-4" />
                  Completed
                </>
              ) : (
                <>
                  <Target className="w-4 h-4" />
                  Draft
                </>
              )}
            </div>
          </div>
          
          <span className="text-sm text-gray-500">
            Last updated: {new Date(reflection.updatedAt).toLocaleDateString()}
          </span>
        </div>
      </div>
    </div>
  );
}